#!/bin/sh
# Generate src/llama_cpp_onicai_fork/common/build-info.cpp
#
# Upstream llama.cpp b10076 changed build-info from global variables
# (LLAMA_BUILD_NUMBER, LLAMA_COMMIT, ...) to functions declared in
# common/build-info.h (llama_build_number(), llama_commit(), ...), and now
# generates the file via CMake. icpp-pro does not use CMake, and the vendored
# scripts/build-info.sh still emits the obsolete variable form, so we generate
# it here instead.
#
# Usage: sh scripts/build-info-cpp.sh <path-to-clang>

set -e

CC=$1
FORK_DIR=$(dirname "$0")/../src/llama_cpp_onicai_fork

build_number="0"
build_commit="unknown"
build_compiler="unknown"
build_target="unknown"

if out=$(git -C "$FORK_DIR" rev-list --count HEAD 2>/dev/null); then
    build_number=$(printf '%s' "$out" | tr -d '\n')
fi

if out=$(git -C "$FORK_DIR" rev-parse --short HEAD 2>/dev/null); then
    build_commit=$(printf '%s' "$out" | tr -d '\n')
fi

if out=$($CC --version 2>/dev/null | head -1); then
    build_compiler=$out
fi

if out=$($CC -dumpmachine 2>/dev/null); then
    build_target=$out
fi

cat <<EOF
// Generated by scripts/build-info-cpp.sh — do not edit.
#include "build-info.h"

#include <cstdio>

int llama_build_number(void) {
    return ${build_number};
}

const char * llama_commit(void) {
    return "${build_commit}";
}

const char * llama_compiler(void) {
    return "${build_compiler}";
}

const char * llama_build_target(void) {
    return "${build_target}";
}

const char * llama_build_info(void) {
    return "b${build_number} (${build_commit}) with ${build_compiler} for ${build_target}";
}

void llama_print_build_info(void) {
    fprintf(stderr, "%s\n", llama_build_info());
}
EOF
