name: Release llama_cpp_canister

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for the release (e.g., v1.0.0)"
        required: true

jobs:
  check-cicd-mac-status:
    name: Check if cicd-mac succeeded
    runs-on: macos-latest
    steps:
      - name: Set up GitHub CLI
        run: echo "GH_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

      - name: Get the latest `cicd-mac` run status
        run: |
          echo "Fetching the latest run of cicd-mac..."
          latest_run=$(gh run list --workflow="cicd-mac.yml" --limit 1 --json conclusion --jq '.[0].conclusion')
          if [ "$latest_run" != "success" ]; then
            echo "The latest cicd-mac run was not successful. Exiting."
            exit 1
          fi
          echo "The latest cicd-mac run was successful."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    name: Build and Release
    needs: check-cicd-mac-status  # Ensures this job runs only if check-cicd-mac-status is successful
    runs-on: macos-latest

    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v4
        with:
          name: llama_cpp_artifacts
          path: build/

      - name: List downloaded artifacts
        run: ls -l build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
          tag_name: ${{ github.event.inputs.tag }}
          release_name: "Release ${{ github.event.inputs.tag }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}